global:
    scrape_interval: 15s
    evaluation_interval: 15s
rule_files:
    - /etc/prometheus/rules/*.yml

scrape_configs:
    - job_name: 'oracle_nodes'
      static_configs:
        - targets:
            - 'node-1:9090'
            - 'node-2:9090'
            - 'node-3:9090'